// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etyjqjwoawvrkxoqinsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eWpxandvYXd2cmt4b3FpbnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDQ4MjQsImV4cCI6MjA3MzM4MDgyNH0.9GX2b4lQSwS2qzmxaeUVvYpGPe4khKZVtBrejiorOZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});